### PR TITLE
Restricting turned-in files

### PR DESCRIPTION
**Pull request by panagosg7**
@ranjitjhala Can you confirm that **these are exactly the files they need to turn in**?

I tested the command `make turnin` on `ieng6`.

### CODE REVIEW

**Comment by ranjitjhala** [comment]
Why restrict the other paths?


On Tue, Oct 4, 2016 at 10:04 AM, Panagiotis Vekris <notifications@github.com

**Comment by panagosg7** [comment]
1. Compactness
2. Harness against changing files that are not supposed to change. (The command lists the files that are tar-ed.). This could also be mentioned in the description of the assignment.

**Comment by ranjitjhala** [comment]
(1) doesn't seem like a big deal (the tar-balls are source only so quite
tiny.)

(2) ​Lets not change the spec this late in the game.

I worry we'll get a bunch of -- but it compiled when *I* ran it --
complaints.

The only real reason would be if it somehow made things "easier" to grade,
but I don't see how...


​

**Comment by panagosg7** [comment]
Sure.

**Pull request closed without merging**
